// <auto-generated />
namespace LearnerProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_remove_relation_classroom_and_course : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_remove_relation_classroom_and_course));
        
        string IMigrationMetadata.Id
        {
            get { return "202404041745345_mig_remove_relation_classroom_and_course"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
